######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 22 15:02:08 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network
QT += testlib

# Input
HEADERS += main.hh
HEADERS += netsocket.hh
HEADERS += test.hh

SOURCES += main.cc
SOURCES += netsocket.cc
SOURCES += test.cc
